
language: java
jdk:
 - openjdk8

addons:
  sonarcloud:
    organization: "briceroro"
    token:
      secure: "****************************" # encrypted value of your token

before_script:
    - cd $TRAVIS_BUILD_DIR/src

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=*************************
